// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjuXkSwPXTMZq2PpKee7IM1-LmqU8DL8',
    appId: '1:507041746157:web:c61a3b7629370c976850e4',
    messagingSenderId: '507041746157',
    projectId: 'timeluxe-app',
    authDomain: 'timeluxe-app.firebaseapp.com',
    storageBucket: 'timeluxe-app.appspot.com',
    measurementId: 'G-LQW38EJDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7iDOG_GTd2dx-mKZLqp1fcGFJmU-drM',
    appId: '1:507041746157:android:054eceb0e9e9d6cb6850e4',
    messagingSenderId: '507041746157',
    projectId: 'timeluxe-app',
    storageBucket: 'timeluxe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOHWY-5QukOedvbg3qKq1zm6fTiWuOMM',
    appId: '1:507041746157:ios:ee5125664ff20a5e6850e4',
    messagingSenderId: '507041746157',
    projectId: 'timeluxe-app',
    storageBucket: 'timeluxe-app.appspot.com',
    iosClientId: '507041746157-i1jrg8ifopgn8lmive7vquciqfdrvln5.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeLuxe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtOHWY-5QukOedvbg3qKq1zm6fTiWuOMM',
    appId: '1:507041746157:ios:736e59510f2e0bd86850e4',
    messagingSenderId: '507041746157',
    projectId: 'timeluxe-app',
    storageBucket: 'timeluxe-app.appspot.com',
    iosClientId: '507041746157-v8m3a7qt4qvqdcnnpus9t5im20aahq49.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeLuxe.RunnerTests',
  );
}
